# Generated by Django 2.0.3 on 2018-03-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ManyToManyField(to='album.Image'),
        ),
    ]
