# Generated by Django 2.0.3 on 2018-03-31 10:27

import album.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20180331_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='image',
        ),
        migrations.AddField(
            model_name='album',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=album.models.get_image_filename),
            preserve_default=False,
        ),
    ]
