# Generated by Django 2.0.3 on 2018-04-01 19:45

import album.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0003_auto_20180331_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='album',
            name='album_name',
        ),
        migrations.AddField(
            model_name='album',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='album',
            name='password',
            field=models.CharField(default=album.models.password_generator, max_length=6, unique=True),
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=album.models.slug_generator, max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='image',
            name='publisher',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='images', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
    ]
