# Generated by Django 2.0.3 on 2018-04-03 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_image_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='album.Album'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='album/'),
        ),
    ]
