# Generated by Django 2.0.3 on 2018-04-03 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0009_remove_image_album'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Album')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='album.Image')),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='album.Album')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='albumcollection',
            unique_together={('album', 'image')},
        ),
        migrations.AlterIndexTogether(
            name='albumcollection',
            index_together={('album', 'image')},
        ),
    ]
