# Generated by Django 2.0.3 on 2018-04-03 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0010_auto_20180403_2105'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
