# Generated by Django 2.0.3 on 2018-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0011_album_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='album',
        ),
        migrations.RemoveField(
            model_name='like',
            name='album',
        ),
        migrations.RemoveField(
            model_name='album',
            name='like',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
